
project_id = "supabase"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://localhost:3000",
  "http://localhost:5173", 
  "https://localhost:5173", 
  "https://i-blue.dev", 
  "http://i-blue.dev", 
  "https://www.i-blue.dev", 
  "http://www.i-blue.dev",
  "https://i-blue.dev/callback/github",
  "https://www.i-blue.dev/callback/github",
  "http://localhost:3000/callback/github",
  "http://localhost:5173/callback/github",
  "https://localhost:3000/callback/github",
  "https://localhost:5173/callback/github",
  "http://i-blue.dev/callback/github",
  "http://www.i-blue.dev/callback/github"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = true

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = true
client_id = ""
secret = ""
redirect_uri = "https://i-blue.dev/callback/github"

[functions]
enabled = true

[functions.github-auth]
verify_jwt = true

[functions.github-repos]
verify_jwt = true

[functions.get-env]
verify_jwt = true
