
project_id = "vcywiyvbfrylffwfzsny"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[realtime]
enabled = true
port = 54326

[functions.chat]
verify_jwt = false

[functions.generate-app]
verify_jwt = false
